-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.attendance_checkin (
  id integer NOT NULL DEFAULT nextval('attendance_checkin_id_seq'::regclass),
  employee_id character varying NOT NULL,
  employee_name character varying NOT NULL,
  work_date date NOT NULL,
  check_in_time timestamp with time zone,
  check_out_time timestamp with time zone,
  shift integer,
  gps_location_in text,
  gps_location_out text,
  is_checked_in boolean DEFAULT false,
  is_checked_out boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT attendance_checkin_pkey PRIMARY KEY (id),
  CONSTRAINT fk_checkin_employee FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id)
);
CREATE TABLE public.attendance_punctuality (
  id integer NOT NULL DEFAULT nextval('attendance_punctuality_id_seq'::regclass),
  employee_id character varying NOT NULL,
  work_date date NOT NULL,
  wage_period_id integer,
  scheduled_in_time time without time zone,
  check_in_time time without time zone,
  early_minutes integer DEFAULT 0,
  is_punctual boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT attendance_punctuality_pkey PRIMARY KEY (id),
  CONSTRAINT fk_punctuality_employee FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id),
  CONSTRAINT fk_punctuality_period FOREIGN KEY (wage_period_id) REFERENCES public.wage_periods(id)
);
CREATE TABLE public.attendance_scans (
  id integer NOT NULL DEFAULT nextval('attendance_scans_id_seq'::regclass),
  machine_id character varying NOT NULL,
  scan_date date NOT NULL,
  scan_time time without time zone NOT NULL,
  employee_id character varying NOT NULL,
  scan_type integer NOT NULL CHECK (scan_type = ANY (ARRAY[1, 2])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT attendance_scans_pkey PRIMARY KEY (id),
  CONSTRAINT fk_employee FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id)
);
CREATE TABLE public.auto_adjustment_logs (
  id bigint NOT NULL DEFAULT nextval('auto_adjustment_logs_id_seq'::regclass),
  employee_id text NOT NULL,
  year integer NOT NULL,
  month integer NOT NULL,
  period integer NOT NULL CHECK (period = ANY (ARRAY[1, 2])),
  adjustment_type text NOT NULL CHECK (adjustment_type = ANY (ARRAY['income'::text, 'deduction'::text])),
  category text NOT NULL,
  amount numeric NOT NULL,
  details jsonb,
  calculation_run_id text,
  calculated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT auto_adjustment_logs_pkey PRIMARY KEY (id),
  CONSTRAINT auto_adjustment_logs_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id)
);
CREATE TABLE public.daily_attendance (
  id integer NOT NULL DEFAULT nextval('daily_attendance_id_seq'::regclass),
  employee_id character varying NOT NULL,
  work_date date NOT NULL,
  check_in_time time without time zone,
  check_out_time time without time zone,
  scheduled_in_time time without time zone,
  scheduled_out_time time without time zone,
  actual_hours numeric DEFAULT 0,
  ot_hours numeric DEFAULT 0,
  is_holiday boolean DEFAULT false,
  is_leave boolean DEFAULT false,
  late boolean DEFAULT false,
  late_hours numeric DEFAULT 0,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  ot_normal_hours numeric DEFAULT 0,
  ot_special_hours numeric DEFAULT 0,
  ot_premium_hours numeric DEFAULT 0,
  ot_normal_hours_multiplied numeric DEFAULT 0,
  ot_special_hours_multiplied numeric DEFAULT 0,
  ot_premium_hours_multiplied numeric DEFAULT 0,
  ot_hours_multiplied numeric DEFAULT 0,
  CONSTRAINT daily_attendance_pkey PRIMARY KEY (id),
  CONSTRAINT fk_daily_employee FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id)
);
CREATE TABLE public.daily_wages (
  id integer NOT NULL DEFAULT nextval('daily_wages_id_seq'::regclass),
  employee_id character varying NOT NULL,
  work_date date NOT NULL,
  wage_period_id integer,
  actual_hours numeric DEFAULT 0,
  ot_normal_hours numeric DEFAULT 0,
  ot_special_hours numeric DEFAULT 0,
  ot_premium_hours numeric DEFAULT 0,
  perhr_salary numeric,
  perday_salary numeric,
  base_wage numeric DEFAULT 0,
  ot1_wage numeric DEFAULT 0,
  ot2_wage numeric DEFAULT 0,
  ot3_wage numeric DEFAULT 0,
  daily_total_wage numeric DEFAULT 0,
  is_holiday boolean DEFAULT false,
  is_leave boolean DEFAULT false,
  late boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT daily_wages_pkey PRIMARY KEY (id),
  CONSTRAINT fk_daily_wage_employee FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id),
  CONSTRAINT fk_daily_wage_period FOREIGN KEY (wage_period_id) REFERENCES public.wage_periods(id)
);
CREATE TABLE public.employee_wage_summary_ytd (
  id integer NOT NULL DEFAULT nextval('employee_wage_summary_ytd_id_seq'::regclass),
  employee_id character varying NOT NULL,
  year integer NOT NULL,
  ytd_gross_wage numeric DEFAULT 0,
  ytd_attendance_bonus numeric DEFAULT 0,
  ytd_total_income numeric DEFAULT 0,
  ytd_sso numeric DEFAULT 0,
  ytd_tax numeric DEFAULT 0,
  ytd_other_deductions numeric DEFAULT 0,
  ytd_total_deductions numeric DEFAULT 0,
  ytd_net_wage numeric DEFAULT 0,
  total_periods_paid integer DEFAULT 0,
  total_days_worked integer DEFAULT 0,
  total_ot_hours numeric DEFAULT 0,
  last_updated_period_id integer,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT employee_wage_summary_ytd_pkey PRIMARY KEY (id),
  CONSTRAINT fk_ytd_employee FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id)
);
CREATE TABLE public.employee_ytd_summary (
  id integer NOT NULL DEFAULT nextval('employee_ytd_summary_id_seq'::regclass),
  employee_id character varying NOT NULL,
  year integer NOT NULL,
  ytd_gross_wage numeric DEFAULT 0,
  ytd_ot_wage numeric DEFAULT 0,
  ytd_attendance_bonus numeric DEFAULT 0,
  ytd_income numeric DEFAULT 0,
  ytd_total_income numeric DEFAULT 0,
  ytd_sso numeric DEFAULT 0,
  ytd_tax numeric DEFAULT 0,
  ytd_deduction numeric DEFAULT 0,
  ytd_total_deduction numeric DEFAULT 0,
  ytd_net_wage numeric DEFAULT 0,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT employee_ytd_summary_pkey PRIMARY KEY (id),
  CONSTRAINT fk_ytd_employee FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id)
);
CREATE TABLE public.employees (
  id integer NOT NULL DEFAULT nextval('employees_id_seq'::regclass),
  employee_id character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  department character varying NOT NULL,
  perday_salary numeric,
  perhr_salary numeric,
  bank_id integer,
  bank_account text,
  identity_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  line_id_employ text,
  division_code character varying,
  section_code character varying,
  address text,
  status character varying DEFAULT 'active'::character varying,
  removed_at timestamp with time zone,
  removed_by character varying,
  remarks text,
  line_id_hr text,
  section character varying,
  position character varying,
  gender character varying,
  nationality character varying,
  citizenship character varying,
  religion character varying,
  birth_date date,
  start_date date,
  tax_id character varying,
  social_security character varying,
  provident_fund numeric DEFAULT 0.0,
  company_provident_fund numeric DEFAULT 0.0,
  provident_fund_deduction numeric DEFAULT 0.0,
  social_fund_deduction numeric DEFAULT 0.0,
  life_insurance numeric DEFAULT 0.0,
  housing_loan numeric DEFAULT 0.0,
  teacher_fund numeric DEFAULT 0.0,
  rmf_fund numeric DEFAULT 0.0,
  department_code character varying,
  position_allowance numeric DEFAULT 0,
  phone_allowance numeric DEFAULT 0,
  other_allowance numeric DEFAULT 0,
  defective_work_deduction numeric DEFAULT 0,
  tax_allowance numeric DEFAULT 60000,
  spouse_allowance numeric DEFAULT 0,
  child_allowance numeric DEFAULT 0,
  number_of_children integer DEFAULT 0,
  monthly_salary numeric DEFAULT 0.00,
  employment_type character varying,
  CONSTRAINT employees_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fifty_tawi (
  id integer NOT NULL DEFAULT nextval('fifty_tawi_id_seq'::regclass),
  employee_id character varying,
  tax_identification_number character varying,
  fifty_tawi_number character varying,
  request_date date,
  approve_date date,
  CONSTRAINT fifty_tawi_pkey PRIMARY KEY (id),
  CONSTRAINT fifty_tawi_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.personal_data(employee_id)
);
CREATE TABLE public.income_deduction_master (
  id integer NOT NULL DEFAULT nextval('income_deduction_master_id_seq'::regclass),
  category character varying NOT NULL CHECK (category::text = ANY (ARRAY['income'::character varying, 'deduction'::character varying]::text[])),
  item_name character varying NOT NULL UNIQUE,
  item_name_th character varying NOT NULL,
  include_in_sso boolean NOT NULL DEFAULT false,
  is_fixed boolean NOT NULL DEFAULT false,
  default_amount numeric DEFAULT 0,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT income_deduction_master_pkey PRIMARY KEY (id)
);
CREATE TABLE public.income_deduction_records (
  id integer NOT NULL DEFAULT nextval('income_deduction_records_id_seq'::regclass),
  employee_id character varying NOT NULL,
  pay_period_month integer NOT NULL CHECK (pay_period_month >= 1 AND pay_period_month <= 12),
  pay_period_year integer NOT NULL,
  pay_period integer NOT NULL CHECK (pay_period = ANY (ARRAY[1, 2])),
  record_type character varying NOT NULL CHECK (record_type::text = ANY (ARRAY['income'::character varying, 'deduction'::character varying]::text[])),
  item_name character varying NOT NULL,
  amount numeric NOT NULL DEFAULT 0 CHECK (amount >= 0::numeric),
  include_in_sso boolean NOT NULL DEFAULT false,
  is_fixed boolean NOT NULL DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by character varying,
  CONSTRAINT income_deduction_records_pkey PRIMARY KEY (id),
  CONSTRAINT fk_income_deduction_employee FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id)
);
CREATE TABLE public.leave_records (
  id integer NOT NULL DEFAULT nextval('leave_records_id_seq'::regclass),
  employee_id character varying NOT NULL,
  leave_date date NOT NULL,
  leave_type character varying DEFAULT 'Personal'::character varying,
  reason text,
  leave_able boolean DEFAULT false,
  rejected_reason text,
  created_by character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  status character varying DEFAULT 'pending'::character varying,
  is_paid boolean DEFAULT false,
  leave_hours integer NOT NULL DEFAULT 8 CHECK (leave_hours >= 1 AND leave_hours <= 24),
  deduct_wage boolean NOT NULL DEFAULT false,
  deduct_diligence boolean NOT NULL DEFAULT false,
  CONSTRAINT leave_records_pkey PRIMARY KEY (id),
  CONSTRAINT fk_leave_employee FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id)
);
CREATE TABLE public.monthly_payroll (
  id integer NOT NULL DEFAULT nextval('monthly_payroll_id_seq'::regclass),
  employee_id character varying NOT NULL,
  year integer NOT NULL,
  month integer NOT NULL CHECK (month >= 1 AND month <= 12),
  basic_salary numeric DEFAULT 0,
  ot_amount numeric DEFAULT 0,
  allowance_total numeric DEFAULT 0,
  bonus numeric DEFAULT 0,
  other_income numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  sso_employee numeric DEFAULT 0,
  sso_employer numeric DEFAULT 0,
  provident_fund_employee numeric DEFAULT 0,
  provident_fund_employer numeric DEFAULT 0,
  student_loan numeric DEFAULT 0,
  other_deduction numeric DEFAULT 0,
  gross_salary numeric DEFAULT 0,
  total_deduction numeric DEFAULT 0,
  net_salary numeric DEFAULT 0,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'approved'::character varying, 'paid'::character varying, 'cancelled'::character varying]::text[])),
  generated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  approved_at timestamp without time zone,
  approved_by character varying,
  paid_at timestamp without time zone,
  notes text,
  CONSTRAINT monthly_payroll_pkey PRIMARY KEY (id),
  CONSTRAINT monthly_payroll_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.personal_data(employee_id)
);
CREATE TABLE public.morning_ot_allowances (
  id integer NOT NULL DEFAULT nextval('morning_ot_allowances_id_seq'::regclass),
  employee_id character varying NOT NULL,
  year integer NOT NULL,
  month integer NOT NULL,
  period integer NOT NULL CHECK (period = ANY (ARRAY[1, 2])),
  allowed_hours numeric NOT NULL DEFAULT 0,
  calculated_hours numeric DEFAULT 0,
  actual_hours numeric DEFAULT LEAST(allowed_hours, COALESCE(calculated_hours, (0)::numeric)),
  selected_dates jsonb,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by character varying,
  CONSTRAINT morning_ot_allowances_pkey PRIMARY KEY (id),
  CONSTRAINT morning_ot_allowances_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id)
);
CREATE TABLE public.payroll_adjustment (
  id integer NOT NULL DEFAULT nextval('payroll_adjustment_id_seq'::regclass),
  employee_id character varying NOT NULL,
  year integer NOT NULL,
  month integer NOT NULL,
  adjustment_type character varying NOT NULL CHECK (adjustment_type::text = ANY (ARRAY['add'::character varying, 'deduct'::character varying]::text[])),
  category character varying NOT NULL,
  amount numeric NOT NULL,
  description text,
  created_by character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT payroll_adjustment_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_adjustment_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.personal_data(employee_id)
);
CREATE TABLE public.payroll_history (
  id integer NOT NULL DEFAULT nextval('payroll_history_id_seq'::regclass),
  payroll_id integer NOT NULL,
  employee_id character varying NOT NULL,
  action character varying NOT NULL,
  action_by character varying,
  action_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  old_status character varying,
  new_status character varying,
  notes text,
  CONSTRAINT payroll_history_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_history_payroll_id_fkey FOREIGN KEY (payroll_id) REFERENCES public.monthly_payroll(id)
);
CREATE TABLE public.payroll_ytd (
  id integer NOT NULL DEFAULT nextval('payroll_ytd_id_seq'::regclass),
  employee_id character varying NOT NULL,
  tax_year integer NOT NULL,
  ytd_earning numeric DEFAULT 0,
  ytd_tax numeric DEFAULT 0,
  ytd_sso numeric DEFAULT 0,
  ytd_ot numeric DEFAULT 0,
  ytd_bonus numeric DEFAULT 0,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT payroll_ytd_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_ytd_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.personal_data(employee_id)
);
CREATE TABLE public.period_wages (
  id integer NOT NULL DEFAULT nextval('period_wages_id_seq'::regclass),
  employee_id character varying NOT NULL,
  wage_period_id integer NOT NULL,
  total_base_wage numeric DEFAULT 0,
  total_ot1_wage numeric DEFAULT 0,
  total_ot2_wage numeric DEFAULT 0,
  total_ot3_wage numeric DEFAULT 0,
  gross_wage numeric DEFAULT 0,
  attendance_bonus numeric DEFAULT 0,
  total_days_worked integer DEFAULT 0,
  punctual_days integer DEFAULT 0,
  eligible_for_bonus boolean DEFAULT false,
  total_income numeric DEFAULT 0,
  sso_employee numeric DEFAULT 0,
  tax_withholding numeric DEFAULT 0,
  other_deductions numeric DEFAULT 0,
  total_deductions numeric DEFAULT 0,
  net_wage numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT period_wages_pkey PRIMARY KEY (id),
  CONSTRAINT fk_period_wage_employee FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id),
  CONSTRAINT fk_period_wage_period FOREIGN KEY (wage_period_id) REFERENCES public.wage_periods(id)
);
CREATE TABLE public.personal_data (
  id integer NOT NULL DEFAULT nextval('personal_data_id_seq'::regclass),
  employee_id character varying NOT NULL UNIQUE,
  title_name character varying,
  name character varying,
  nickname character varying,
  gender character varying,
  birth_date date,
  mobile_phone character varying,
  national_id character varying,
  national_idcard_issue_date date,
  national_idcard_expiry_date date,
  national_idcard_issued_place character varying,
  nationality character varying,
  race character varying,
  religion character varying,
  height numeric,
  weight numeric,
  marital_status character varying,
  spouse_title_name character varying,
  spouse_name character varying,
  emergency_contact_name character varying,
  emergency_contact_relation character varying,
  emergency_contact_phone character varying,
  number_of_children integer,
  children_in_school integer,
  children_notin_school integer,
  address character varying,
  line_id character varying,
  CONSTRAINT personal_data_pkey PRIMARY KEY (id)
);
CREATE TABLE public.personal_money (
  id integer NOT NULL DEFAULT nextval('personal_money_id_seq'::regclass),
  employee_id character varying,
  social_security_contribution numeric,
  company_provident_fund numeric,
  employee_provident_fund numeric,
  student_loan_deduction numeric,
  retirement_mutual_fund_deduction numeric,
  rmf_deduction numeric,
  life_insurance_premium numeric,
  housing_loan_interest numeric,
  CONSTRAINT personal_money_pkey PRIMARY KEY (id),
  CONSTRAINT personal_money_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.personal_data(employee_id)
);
CREATE TABLE public.personal_tax (
  id integer NOT NULL DEFAULT nextval('personal_tax_id_seq'::regclass),
  employee_id character varying,
  bank_id character varying,
  bank_account_number character varying,
  tax_identification_number character varying,
  social_security_number character varying,
  provident_fund_number character varying,
  studentloan_number character varying,
  retirement_mutual_fund_number character varying,
  rmf_number character varying,
  life_insurance_number character varying,
  providentfund_entry_date date,
  providentfund_issuance_date date,
  CONSTRAINT personal_tax_pkey PRIMARY KEY (id),
  CONSTRAINT personal_tax_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.personal_data(employee_id)
);
CREATE TABLE public.personal_work_detail (
  id integer NOT NULL DEFAULT nextval('personal_work_detail_id_seq'::regclass),
  employee_id character varying,
  position character varying,
  division character varying,
  department character varying,
  employee_type character varying,
  shift character varying,
  start_time time without time zone,
  start_lunch time without time zone,
  end_lunch time without time zone,
  end_time time without time zone,
  start_working_date date,
  end_working_date date,
  salary numeric,
  daily_wage numeric,
  hourly_wage numeric,
  working_status character varying,
  CONSTRAINT personal_work_detail_pkey PRIMARY KEY (id),
  CONSTRAINT personal_work_detail_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.personal_data(employee_id)
);
CREATE TABLE public.special_holidays (
  id integer NOT NULL DEFAULT nextval('special_holidays_id_seq'::regclass),
  holiday_date date NOT NULL UNIQUE,
  holiday_name character varying NOT NULL,
  is_national boolean DEFAULT true,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT special_holidays_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sso_monthly (
  id integer NOT NULL DEFAULT nextval('sso_monthly_id_seq'::regclass),
  employee_id character varying NOT NULL,
  year integer NOT NULL,
  month integer NOT NULL CHECK (month >= 1 AND month <= 12),
  wage numeric NOT NULL,
  employee_sso numeric NOT NULL,
  employer_sso numeric NOT NULL,
  total_sso numeric NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['paid'::character varying, 'pending'::character varying, 'cancelled'::character varying]::text[])),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  paid_at timestamp without time zone,
  CONSTRAINT sso_monthly_pkey PRIMARY KEY (id),
  CONSTRAINT sso_monthly_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.personal_data(employee_id)
);
CREATE TABLE public.sso_monthly_summary (
  id integer NOT NULL DEFAULT nextval('sso_monthly_summary_id_seq'::regclass),
  employee_id character varying NOT NULL,
  wage_month date NOT NULL,
  period1_income numeric DEFAULT 0,
  period2_income numeric DEFAULT 0,
  total_monthly_income numeric DEFAULT 0,
  sso_base numeric DEFAULT 0,
  sso_rate numeric DEFAULT 0.05,
  period1_sso numeric DEFAULT 0,
  period2_sso numeric DEFAULT 0,
  total_monthly_sso numeric DEFAULT 0,
  employer_sso numeric DEFAULT 0,
  sso_due_date date,
  is_submitted boolean DEFAULT false,
  submitted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sso_monthly_summary_pkey PRIMARY KEY (id),
  CONSTRAINT fk_sso_employee FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id)
);
CREATE TABLE public.tax_calculations (
  id integer NOT NULL DEFAULT nextval('tax_calculations_id_seq'::regclass),
  employee_id character varying NOT NULL,
  wage_period_id integer NOT NULL,
  gross_income numeric DEFAULT 0,
  personal_allowance numeric DEFAULT 0,
  sso_deduction numeric DEFAULT 0,
  other_allowances numeric DEFAULT 0,
  total_allowances numeric DEFAULT 0,
  taxable_income numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  tax_rate numeric DEFAULT 0,
  ytd_income numeric DEFAULT 0,
  ytd_tax numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tax_calculations_pkey PRIMARY KEY (id),
  CONSTRAINT fk_tax_employee FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id),
  CONSTRAINT fk_tax_period FOREIGN KEY (wage_period_id) REFERENCES public.wage_periods(id)
);
CREATE TABLE public.wage_adjustment_logs (
  id bigint NOT NULL DEFAULT nextval('wage_adjustment_logs_id_seq'::regclass),
  adjustment_id bigint,
  employee_id text NOT NULL,
  year integer NOT NULL,
  month integer NOT NULL,
  period integer NOT NULL CHECK (period = ANY (ARRAY[1, 2])),
  adjustment_type text NOT NULL CHECK (adjustment_type = ANY (ARRAY['income'::text, 'deduction'::text])),
  category text NOT NULL,
  amount numeric NOT NULL,
  description text,
  action_type text NOT NULL CHECK (action_type = ANY (ARRAY['create'::text, 'update'::text, 'delete'::text])),
  old_data jsonb,
  performed_by text NOT NULL,
  performed_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT wage_adjustment_logs_pkey PRIMARY KEY (id),
  CONSTRAINT wage_adjustment_logs_adjustment_id_fkey FOREIGN KEY (adjustment_id) REFERENCES public.wage_adjustments(id),
  CONSTRAINT wage_adjustment_logs_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id)
);
CREATE TABLE public.wage_adjustments (
  id integer NOT NULL DEFAULT nextval('wage_adjustments_id_seq'::regclass),
  employee_id character varying NOT NULL,
  year integer NOT NULL,
  month integer NOT NULL,
  period integer NOT NULL CHECK (period = ANY (ARRAY[1, 2])),
  adjustment_type character varying NOT NULL,
  category character varying NOT NULL,
  amount numeric NOT NULL,
  description text,
  created_by character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wage_adjustments_pkey PRIMARY KEY (id),
  CONSTRAINT wage_adjustments_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id)
);
CREATE TABLE public.wage_calculation_log (
  id integer NOT NULL DEFAULT nextval('wage_calculation_log_id_seq'::regclass),
  employee_id character varying NOT NULL,
  year integer NOT NULL,
  month integer NOT NULL,
  period integer NOT NULL,
  calculation_date timestamp with time zone DEFAULT now(),
  details jsonb,
  errors text,
  success boolean DEFAULT true,
  CONSTRAINT wage_calculation_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.wage_details (
  id integer NOT NULL DEFAULT nextval('wage_details_id_seq'::regclass),
  employee_id character varying NOT NULL,
  year integer NOT NULL,
  month integer NOT NULL,
  period integer NOT NULL CHECK (period = ANY (ARRAY[1, 2])),
  employment_type character varying,
  perday_salary numeric DEFAULT 0,
  perhr_salary numeric DEFAULT 0,
  monthly_salary numeric DEFAULT 0,
  total_days integer DEFAULT 0,
  work_days integer DEFAULT 0,
  holiday_work_days integer DEFAULT 0,
  leave_days integer DEFAULT 0,
  absent_days integer DEFAULT 0,
  base_wage numeric DEFAULT 0,
  ot1_hours numeric DEFAULT 0,
  ot2_hours numeric DEFAULT 0,
  ot3_hours numeric DEFAULT 0,
  ot1_wage numeric DEFAULT 0,
  ot2_wage numeric DEFAULT 0,
  ot3_wage numeric DEFAULT 0,
  total_ot_wage numeric DEFAULT 0,
  night_shift_days integer DEFAULT 0,
  night_shift_allowance numeric DEFAULT 0,
  attendance_bonus numeric DEFAULT 0,
  additional_income numeric DEFAULT 0,
  late_minutes integer DEFAULT 0,
  late_deduction numeric DEFAULT 0,
  leave_deduction numeric DEFAULT 0,
  additional_deduction numeric DEFAULT 0,
  gross_income numeric DEFAULT 0,
  total_income numeric DEFAULT 0,
  sso numeric DEFAULT 0,
  tax numeric DEFAULT 0,
  total_deduction numeric DEFAULT 0,
  net_wage numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wage_details_pkey PRIMARY KEY (id),
  CONSTRAINT wage_details_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id)
);
CREATE TABLE public.wage_periods (
  id integer NOT NULL DEFAULT nextval('wage_periods_id_seq'::regclass),
  wage_month date NOT NULL,
  period_number integer NOT NULL CHECK (period_number = ANY (ARRAY[1, 2])),
  work_start_date date NOT NULL,
  work_end_date date NOT NULL,
  payment_date date NOT NULL,
  sso_due_date date,
  is_closed boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wage_periods_pkey PRIMARY KEY (id)
);
CREATE TABLE public.wage_summary (
  id integer NOT NULL DEFAULT nextval('wage_summary_id_seq'::regclass),
  employee_id character varying NOT NULL,
  year integer NOT NULL,
  month integer NOT NULL,
  period integer NOT NULL CHECK (period = ANY (ARRAY[1, 2])),
  base_wage numeric DEFAULT 0,
  ot_wage numeric DEFAULT 0,
  attendance_bonus numeric DEFAULT 0,
  total_income numeric DEFAULT 0,
  sso numeric DEFAULT 0,
  tax numeric DEFAULT 0,
  total_deduction numeric DEFAULT 0,
  net_wage numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  work_days integer DEFAULT 0,
  leave_days integer DEFAULT 0,
  late_minutes integer DEFAULT 0,
  late_deduction numeric DEFAULT 0,
  night_shift_days integer DEFAULT 0,
  night_shift_allowance numeric DEFAULT 0,
  leave_deduction numeric DEFAULT 0,
  additional_income numeric DEFAULT 0,
  additional_deduction numeric DEFAULT 0,
  ot1_hours numeric DEFAULT 0,
  ot2_hours numeric DEFAULT 0,
  ot3_hours numeric DEFAULT 0,
  ot1_wage numeric DEFAULT 0,
  ot2_wage numeric DEFAULT 0,
  ot3_wage numeric DEFAULT 0,
  employment_type character varying,
  CONSTRAINT wage_summary_pkey PRIMARY KEY (id),
  CONSTRAINT fk_wage_employee FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id)
);